# Generated by Django 5.1.3 on 2025-04-23 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_categoria", models.CharField(max_length=200)),
                (
                    "icona",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/categorie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_prodotto", models.CharField(max_length=200)),
                ("ean", models.IntegerField()),
                (
                    "misura",
                    models.CharField(
                        choices=[
                            ("bottiglie", "Vendita a bottiglia"),
                            ("kilo", "Vendita al peso"),
                            ("litro", "Vendita al litro"),
                            ("confezione", "Vendita a confezione"),
                        ],
                        default="confezione",
                        max_length=15,
                    ),
                ),
                (
                    "aliquota_iva",
                    models.CharField(
                        choices=[
                            ("4%", "Iva al 4%"),
                            ("10%", "Iva al 10%"),
                            ("22%", "Iva al 22%"),
                        ],
                        default="22%",
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordini.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "misura",
                    models.CharField(
                        choices=[
                            ("bottiglie", "Vendita a bottiglia"),
                            ("kilo", "Vendita al peso"),
                            ("litro", "Vendita al litro"),
                            ("confezione", "Vendita a confezione"),
                        ],
                        default="confezione",
                        max_length=50,
                    ),
                ),
                ("pezzi_per_confezione", models.FloatField(blank=True, null=True)),
                ("quantita_ordinata", models.IntegerField()),
                (
                    "prezzo_unitario_ordine",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "prezzo_totale_ordine",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "totale_ordine_ivato",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "pdf_ordine",
                    models.FileField(
                        blank=True, null=True, upload_to="media/ordini_pdf/"
                    ),
                ),
                ("data_invio_ordine", models.DateField(blank=True, null=True)),
                ("data_arrivo_previsto", models.DateField(blank=True, null=True)),
                ("data_ricezione_ordine", models.DateField(blank=True, null=True)),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafica.fornitore",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordini.prodotto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ricezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ricezione", models.DateField(auto_now_add=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "ordine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ricezione",
                        to="ordini.ordine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProdottoRicevuto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantita_ricevuta", models.IntegerField()),
                ("data_scadenza", models.DateField(blank=True, null=True)),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordini.prodotto",
                    ),
                ),
                (
                    "ricezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prodotti_ricevuti",
                        to="ordini.ricezione",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Magazzino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantita_in_magazzino", models.IntegerField(default=0)),
                ("data_scadenza", models.DateField(blank=True, null=True)),
                ("data_ingresso", models.DateField(auto_now_add=True)),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordini.prodotto",
                    ),
                ),
            ],
            options={
                "unique_together": {("prodotto", "data_scadenza")},
            },
        ),
        migrations.CreateModel(
            name="ListinoPrezzi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prezzo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("data_inizio_validita", models.DateField()),
                ("data_fine_validita", models.DateField(blank=True, null=True)),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listini_prezzi",
                        to="ordini.prodotto",
                    ),
                ),
            ],
            options={
                "ordering": ["prodotto", "-data_inizio_validita"],
                "unique_together": {("prodotto", "data_inizio_validita")},
            },
        ),
    ]
