# Generated by Django 5.1.3 on 2025-04-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordini", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listinoprezzi",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="listinoprezzi",
            name="prodotto",
        ),
    ]
