# Generated by Django 5.1.3 on 2025-04-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordini", "0002_alter_listinoprezzi_unique_together_and_more"),
        ("vendite", "0004_listinoprezzi_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ListinoPrezzi",
        ),
    ]
