# Generated by Django 4.2.21 on 2025-05-16 06:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(help_text='Targa del veicolo', max_length=10, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modello', models.CharField(max_length=100)),
                ('anno_immatricolazione', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('numero_telaio', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cilindrata', models.PositiveIntegerField(blank=True, help_text='in cc', null=True)),
                ('potenza', models.PositiveIntegerField(blank=True, help_text='in CV', null=True)),
                ('chilometri_iniziali', models.PositiveIntegerField(default=0, help_text="Km all'acquisto")),
                ('chilometri_attuali', models.PositiveIntegerField(default=0, help_text='Km attuali')),
                ('data_acquisto', models.DateField(blank=True, null=True)),
                ('costo_acquisto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attivo', models.BooleanField(default=True)),
                ('disponibile', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automezzi_assegnati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automezzo',
                'verbose_name_plural': 'Automezzi',
                'ordering': ['targa'],
            },
        ),
        migrations.CreateModel(
            name='TipoCarburante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es: Benzina, Diesel, GPL, Metano', max_length=50, unique=True)),
                ('costo_per_litro', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Tipo Carburante',
                'verbose_name_plural': 'Tipi Carburante',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='StatisticheAutomezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_medio', models.DecimalField(decimal_places=2, default=0.0, help_text='L/100km', max_digits=5)),
                ('costo_km_carburante', models.DecimalField(decimal_places=4, default=0.0, help_text='€/km', max_digits=8)),
                ('costo_manutenzioni_anno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_totale_km', models.DecimalField(decimal_places=4, default=0.0, help_text='€/km totale', max_digits=8)),
                ('ultimo_rifornimento', models.DateField(blank=True, null=True)),
                ('ultima_manutenzione', models.DateField(blank=True, null=True)),
                ('aggiornato_al', models.DateTimeField(auto_now=True)),
                ('automezzo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiche', to='automezzi.automezzo')),
            ],
            options={
                'verbose_name': 'Statistiche Automezzo',
                'verbose_name_plural': 'Statistiche Automezzi',
            },
        ),
        migrations.CreateModel(
            name='RifornimentoCarburante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rifornimento', models.DateField(default=datetime.date.today)),
                ('chilometri', models.PositiveIntegerField(help_text='Chilometraggio al momento del rifornimento')),
                ('litri', models.DecimalField(decimal_places=2, help_text='Litri riforniti', max_digits=6)),
                ('costo_totale', models.DecimalField(decimal_places=2, help_text='Costo totale del rifornimento', max_digits=8)),
                ('costo_per_litro', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('distributore', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('foto_scontrino', models.ImageField(blank=True, null=True, upload_to='rifornimenti/scontrini/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifornimenti', to='automezzi.automezzo')),
                ('effettuato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifornimenti_effettuati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rifornimento',
                'verbose_name_plural': 'Rifornimenti',
                'ordering': ['-data_rifornimento'],
            },
        ),
        migrations.CreateModel(
            name='Manutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ordinaria', 'Manutenzione Ordinaria'), ('straordinaria', 'Manutenzione Straordinaria'), ('tagliando', 'Tagliando'), ('riparazione', 'Riparazione'), ('gomme', 'Cambio Gomme'), ('altro', 'Altro')], max_length=20)),
                ('descrizione', models.TextField()),
                ('data_prevista', models.DateField()),
                ('data_effettuata', models.DateField(blank=True, null=True)),
                ('chilometri_manutenzione', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_previsto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('costo_effettivo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('completata', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('file_allegato', models.FileField(blank=True, null=True, upload_to='automezzi/manutenzioni/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutenzioni', to='automezzi.automezzo')),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutenzioni_responsabile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manutenzione',
                'verbose_name_plural': 'Manutenzioni',
                'ordering': ['-data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='EventoAutomezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sinistro', 'Sinistro'), ('furto', 'Furto/Tentato Furto'), ('multa', 'Multa'), ('verifica', 'Verifica/Controllo'), ('altro', 'Altro Evento')], max_length=20)),
                ('data_evento', models.DateField(default=datetime.date.today)),
                ('chilometri', models.PositiveIntegerField(blank=True, null=True)),
                ('descrizione', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('risolto', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('file_allegato', models.FileField(blank=True, null=True, upload_to='automezzi/eventi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='automezzi.automezzo')),
                ('dipendente_coinvolto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_automezzi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Automezzo',
                'verbose_name_plural': 'Eventi Automezzi',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAutomezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('assicurazione', 'Assicurazione'), ('revisione', 'Revisione'), ('bollo', 'Bollo'), ('libretto', 'Libretto di circolazione'), ('altro', 'Altro documento')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_rilascio', models.DateField()),
                ('data_scadenza', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('file_documento', models.FileField(blank=True, null=True, upload_to='automezzi/documenti/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='automezzi.automezzo')),
            ],
            options={
                'verbose_name': 'Documento Automezzo',
                'verbose_name_plural': 'Documenti Automezzi',
                'ordering': ['-data_scadenza'],
            },
        ),
        migrations.AddField(
            model_name='automezzo',
            name='tipo_carburante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automezzi.tipocarburante'),
        ),
    ]
