# Generated by Django 4.2.21 on 2025-05-16 09:09

import automezzi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('anno_immatricolazione', models.PositiveIntegerField()),
                ('chilometri_attuali', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('disponibile', models.BooleanField(default=True)),
                ('bloccata', models.BooleanField(default=False)),
                ('motivo_blocco', models.TextField(blank=True, null=True)),
                ('libretto_fronte', models.ImageField(blank=True, help_text='Fronte del libretto di circolazione', null=True, upload_to=automezzi.models.libretto_upload_path)),
                ('libretto_retro', models.ImageField(blank=True, help_text='Retro del libretto di circolazione', null=True, upload_to=automezzi.models.libretto_upload_path)),
                ('assicurazione', models.FileField(blank=True, help_text='File della polizza assicurativa', null=True, upload_to=automezzi.models.assicurazione_upload_path)),
                ('data_revisione', models.DateField(blank=True, help_text='Data ultima revisione', null=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automezzi_assegnati', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rifornimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('litri', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_totale', models.DecimalField(decimal_places=2, max_digits=7)),
                ('chilometri', models.PositiveIntegerField(help_text='Chilometraggio al momento del rifornimento')),
                ('scontrino', models.ImageField(blank=True, help_text='Foto dello scontrino del rifornimento', null=True, upload_to=automezzi.models.scontrino_upload_path)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifornimenti', to='automezzi.automezzo')),
            ],
        ),
        migrations.CreateModel(
            name='Manutenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('completata', models.BooleanField(default=False)),
                ('allegati', models.FileField(blank=True, help_text='Allegati della manutenzione (fatture, ricevute ecc.)', null=True, upload_to=automezzi.models.allegati_manutenzione_path)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutenzioni', to='automezzi.automezzo')),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAutomezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('furto', 'Furto'), ('fermo', 'Fermo amministrativo'), ('guasto', 'Guasto/avaria'), ('altro', 'Altro')], max_length=20)),
                ('data_evento', models.DateField()),
                ('descrizione', models.TextField(blank=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('file_allegato', models.FileField(blank=True, help_text="Foto, verbali, documenti relativi all'evento", null=True, upload_to=automezzi.models.allegato_evento_path)),
                ('risolto', models.BooleanField(default=False)),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='automezzi.automezzo')),
                ('dipendente_coinvolto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_coinvolto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
