# Generated by Django 4.2.21 on 2025-05-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome o Ragione Sociale', max_length=200)),
                ('indirizzo', models.TextField(blank=True)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('partita_iva', models.CharField(blank=True, max_length=15)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('codice_univoco', models.CharField(blank=True, max_length=10)),
                ('pec', models.EmailField(blank=True, max_length=254)),
                ('tipo_pagamento', models.CharField(choices=[('immediato', 'Immediato'), ('15_giorni', '15 giorni'), ('30_giorni', '30 giorni'), ('60_giorni', '60 giorni'), ('90_giorni', '90 giorni'), ('bonifico', 'Bonifico bancario'), ('assegno', 'Assegno')], default='immediato', max_length=20)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('zona', models.CharField(blank=True, max_length=100)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome o Ragione Sociale', max_length=200)),
                ('indirizzo', models.TextField(blank=True)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('partita_iva', models.CharField(max_length=15)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('categoria', models.CharField(choices=[('materie_prime', 'Materie Prime'), ('semilavorati', 'Semilavorati'), ('servizi', 'Servizi'), ('consulenza', 'Consulenza'), ('software', 'Software/IT'), ('altri', 'Altri')], default='altri', max_length=20)),
                ('tipo_pagamento', models.CharField(choices=[('immediato', 'Immediato'), ('15_giorni', '15 giorni'), ('30_giorni', '30 giorni'), ('60_giorni', '60 giorni'), ('90_giorni', '90 giorni'), ('bonifico', 'Bonifico bancario')], default='30_giorni', max_length=20)),
                ('referente_nome', models.CharField(blank=True, max_length=100)),
                ('referente_telefono', models.CharField(blank=True, max_length=20)),
                ('referente_email', models.EmailField(blank=True, max_length=254)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rappresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('indirizzo', models.TextField(blank=True)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('partita_iva', models.CharField(blank=True, max_length=15)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('percentuale_provvigione', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentuale di provvigione (0-100)', max_digits=5)),
                ('zona_competenza', models.CharField(blank=True, max_length=200)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rappresentante',
                'verbose_name_plural': 'Rappresentanti',
                'ordering': ['dipendente__last_name', 'dipendente__first_name'],
            },
        ),
    ]
