# Generated by Django 4.2.21 on 2025-05-14 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rappresentante',
            name='dipendente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rappresentante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rappresentante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='anagrafica.rappresentante'),
        ),
    ]
